from openai import OpenAI
from fpdf import FPDF, XPos, YPos
from datetime import datetime
import re

def clean_text(text: str) -> str:
    text = text.encode("latin-1", "replace").decode("latin-1")
    text = re.sub(r'\*+', '', text)
    text = re.sub(r'#+\s*', '', text)
    text = re.sub(r'-{2,}', '', text)
    return text.strip()
def report_agent1(system_prompt, user_prompt):
    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key="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",
    )
    response_text = ""
    if True:

        response_text = ""

        completion = client.chat.completions.create(
            extra_body={},
            model="nvidia/nemotron-3-super-120b-a12b:free",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            stream=True
        )

        for chunk in completion:
            if chunk.choices[0].delta.content:
                response_text += chunk.choices[0].delta.content

    return response_text


def report_agent(conversation: list) -> bytes:
    print("[Report Agent] Generating report from conversation...")

    convo_text = ""
    for msg in conversation:
        role = "User" if msg["role"] == "user" else "Research Agent"
        convo_text += f"{role}: {msg['content']}\n\n"
      
    system_prompt = """
    You are a professional research report writer.

    You will be given a research conversation between a user and an AI research agent.
    Convert it into a clean, structured research report.

    Output format requirements:
    - Write the report in plain text
    - Use exactly these main section headings:
      Title
      Executive Summary
      Key Findings
      Detailed Analysis
      Conclusion
      Sources Consulted
    - Write every main heading on its own line and in bold letters
    - For subheadings, write them on their own line and prefix them with: SUBHEADING and in bold letters.
    - Do not use markdown symbols such as #, *, -, or bullet points
    - Do not number headings
    - Do not include the conversation itself, only the insights from it
    - Do not make up any information not present in the conversation
    - Use formal, professional language
    - Use normal paragraphs for body text

    Example format:

    Title
    AI Adoption in Healthcare

    Executive Summary
    This report examines ...

    Key Findings
    SUBHEADING: Adoption Trends
    Healthcare organizations ...

    SUBHEADING: Key Risks
    The main concerns include ...

    Detailed Analysis
    SUBHEADING: Market Context
    ...

    Conclusion
    ...

    Sources Consulted
    https://example.com
    """

    user_prompt = f"""
Here is the research conversation:

{convo_text}

Now convert this into a structured professional research report.
"""

    report_text = report_agent1(system_prompt, user_prompt)
    print("[Report Agent] Report text generated.")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(15, 20, 15)
    pdf.set_auto_page_break(auto=True, margin=20)

    pdf.set_font("Helvetica", "B", size=18)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, " A Report by Autonomous AI Research Agent", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(180, 180, 180)
    pdf.cell(0, 6, f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", align="C")
    pdf.ln(10)

    pdf.set_text_color(30, 30, 30)
    usable_width = pdf.w - pdf.l_margin - pdf.r_margin

    for line in report_text.split("\n"):
        line = clean_text(line)
        if not line:
            pdf.ln(4)
            continue

        pdf.set_x(pdf.l_margin)

        if re.match(r'^\d+\.', line) or line.isupper():
            pdf.set_font("Helvetica", "B", size=13)
            pdf.set_text_color(15, 15, 15)
            pdf.ln(4)
            pdf.multi_cell(
                usable_width, 8, line,
                new_x=XPos.LMARGIN, new_y=YPos.NEXT
            )
        else:
            pdf.set_font("Helvetica", size=11)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(
                usable_width, 7, line,
                new_x=XPos.LMARGIN, new_y=YPos.NEXT
            )

    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", size=8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "Generated by Autonomous AI Research Agent", align="C")

    return bytes(pdf.output())
